version: "3.9"

services:
  db_users:
    image: mariadb:11.2.3
    restart: always
    environment:
      MARIADB_USER: springuser
      MARIADB_PASSWORD: ThePassword
      MARIADB_DATABASE: db_users
      MARIADB_ROOT_PASSWORD: ThePassword
    #volumes:
    #  - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
    container_name: db_users

  users_management:

    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_USERNAME=springuser
      - DB_PASSWORD=ThePassword
      - DB_URL=jdbc:mariadb://db_users:3306/db_users
      - SECURITY_USER=pablo
      - SECURITY_PASSWORD=1234
    depends_on:
      - db_users
    container_name: users_management